twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig'] 
    globals:
        url_images: "/images/"
        url_images_produits: "/images/produits/"